/**
 * Mock Documents for Demo Mode
 */

import {
  DocumentStatus,
  ClassificationConfidence,
  O1Criterion,
} from '@/types/enums';

import type { TalentDocument } from '@/types/models';

// ============================================================================
// TALENT DOCUMENTS
// ============================================================================

export const DEMO_TALENT_DOCUMENTS: TalentDocument[] = [
  // Sarah Chen's Documents (talent-profile-1)
  {
    id: 'doc-1',
    talent_id: 'talent-profile-1',
    title: 'ACM Best Paper Award 2023',
    description: 'Award certificate for Best Paper at ACM Conference on AI and Machine Learning',
    file_url: '/demo/documents/award-certificate.pdf',
    file_name: 'acm-best-paper-2023.pdf',
    file_type: 'application/pdf',
    file_size: 245000,
    criterion: O1Criterion.AWARDS,
    auto_classified_criterion: O1Criterion.AWARDS,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Award certificate from major professional association (ACM) for recognized excellence in research.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-10T10:00:00Z',
    review_notes: 'Verified authentic ACM award certificate',
    score_impact: 10,
    extraction_method: 'pdf',
    extraction_confidence: 0.95,
    extracted_text: 'Association for Computing Machinery\nBest Paper Award\nAwarded to: Dr. Sarah Chen\nFor: "Attention Is All You Need: Revisited"\nACM Conference on AI and Machine Learning 2023',
    ai_reasoning: 'This document is clearly an award certificate from ACM, a major professional organization in computing. The award recognizes outstanding research, meeting the O-1 criterion for nationally or internationally recognized prizes or awards.',
    created_at: '2024-11-01T10:00:00Z',
    updated_at: '2024-11-10T10:00:00Z',
  },
  {
    id: 'doc-2',
    talent_id: 'talent-profile-1',
    title: 'NeurIPS Program Committee Invitation',
    description: 'Official invitation to serve on NeurIPS 2023 Program Committee',
    file_url: '/demo/documents/neurips-pc.pdf',
    file_name: 'neurips-pc-invitation.pdf',
    file_type: 'application/pdf',
    file_size: 128000,
    criterion: O1Criterion.JUDGING,
    auto_classified_criterion: O1Criterion.JUDGING,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Invitation to serve as judge/reviewer for major ML conference.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-10T10:00:00Z',
    review_notes: 'Verified NeurIPS PC membership',
    score_impact: 8,
    extraction_method: 'pdf',
    extraction_confidence: 0.92,
    extracted_text: 'Neural Information Processing Systems (NeurIPS) 2023\nProgram Committee Invitation\n\nDear Dr. Chen,\n\nWe are pleased to invite you to serve on the Program Committee for NeurIPS 2023...',
    ai_reasoning: 'This document demonstrates the beneficiary has been asked to judge the work of others in their field. NeurIPS is one of the top venues in machine learning, so serving on its program committee is strong evidence of expertise.',
    created_at: '2024-11-02T10:00:00Z',
    updated_at: '2024-11-10T10:00:00Z',
  },
  {
    id: 'doc-3',
    talent_id: 'talent-profile-1',
    title: 'Google Scholar Profile - Citation Report',
    description: 'Screenshot showing publication count and citations',
    file_url: '/demo/documents/scholar-profile.pdf',
    file_name: 'google-scholar-citations.pdf',
    file_type: 'application/pdf',
    file_size: 890000,
    criterion: O1Criterion.SCHOLARLY_ARTICLES,
    auto_classified_criterion: O1Criterion.SCHOLARLY_ARTICLES,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Evidence of significant scholarly publication record with high impact.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-10T10:00:00Z',
    review_notes: 'Verified 52 publications, h-index 34, 8500+ citations',
    score_impact: 12,
    extraction_method: 'pdf',
    extraction_confidence: 0.88,
    extracted_text: 'Google Scholar\nSarah Chen\nCitations: 8,523\nH-index: 34\nPublications: 52\n\nHighly cited papers:\n1. "Novel Attention Mechanisms" - 1,234 citations\n2. "Scaling Language Models" - 987 citations...',
    ai_reasoning: 'The publication metrics (52 papers, h-index of 34, 8500+ citations) demonstrate a substantial body of scholarly work with significant impact in the field. This strongly supports the scholarly articles criterion.',
    created_at: '2024-11-03T10:00:00Z',
    updated_at: '2024-11-10T10:00:00Z',
  },
  {
    id: 'doc-11',
    talent_id: 'talent-profile-1',
    title: 'Patent Grant - Attention Mechanism',
    description: 'USPTO patent for novel attention mechanism in neural networks',
    file_url: '/demo/documents/patent-attention.pdf',
    file_name: 'patent-us-12345678.pdf',
    file_type: 'application/pdf',
    file_size: 2100000,
    criterion: O1Criterion.ORIGINAL_CONTRIBUTIONS,
    auto_classified_criterion: O1Criterion.ORIGINAL_CONTRIBUTIONS,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Patent grant demonstrating original contribution to the field.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-15T10:00:00Z',
    review_notes: 'Verified USPTO patent - significant technical innovation',
    score_impact: 10,
    extraction_method: 'pdf',
    extraction_confidence: 0.94,
    extracted_text: 'United States Patent\nPatent No.: US 12,345,678 B2\nDate: January 15, 2024\n\nINVENTOR: Sarah Chen\n\nTITLE: Adaptive Multi-Head Attention Mechanism for Efficient Language Model Training...',
    ai_reasoning: 'A granted US patent demonstrates original contributions of major significance. The patent describes a novel technical innovation that has been reviewed and approved by patent examiners.',
    created_at: '2024-11-14T10:00:00Z',
    updated_at: '2024-11-15T10:00:00Z',
  },

  // Alex Kumar's Documents (talent-profile-2)
  {
    id: 'doc-4',
    talent_id: 'talent-profile-2',
    title: 'Red Dot Design Award 2023',
    description: 'Certificate for Red Dot Best of the Best award',
    file_url: '/demo/documents/red-dot-award.pdf',
    file_name: 'red-dot-2023.pdf',
    file_type: 'application/pdf',
    file_size: 567000,
    criterion: O1Criterion.AWARDS,
    auto_classified_criterion: O1Criterion.AWARDS,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Internationally recognized design award.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-12T10:00:00Z',
    review_notes: 'Verified Red Dot award - prestigious international recognition',
    score_impact: 10,
    extraction_method: 'pdf',
    extraction_confidence: 0.91,
    extracted_text: 'Red Dot Award\nBest of the Best 2023\n\nAwarded to: Alex Kumar\nCategory: Communication Design\nProject: Figma Design System 3.0',
    ai_reasoning: 'The Red Dot Award is one of the world\'s most prestigious design competitions. A "Best of the Best" award represents the highest level of recognition, strongly supporting the awards criterion.',
    created_at: '2024-11-05T10:00:00Z',
    updated_at: '2024-11-12T10:00:00Z',
  },
  {
    id: 'doc-5',
    talent_id: 'talent-profile-2',
    title: 'Fast Company Feature Article',
    description: 'Published article about Alex Kumar\'s design philosophy',
    file_url: '/demo/documents/fast-company-feature.pdf',
    file_name: 'fast-company-alex-kumar.pdf',
    file_type: 'application/pdf',
    file_size: 1234000,
    criterion: O1Criterion.PUBLISHED_MATERIAL,
    auto_classified_criterion: O1Criterion.PUBLISHED_MATERIAL,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Feature article in major publication about the beneficiary.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-12T10:00:00Z',
    review_notes: 'Verified Fast Company feature - significant media coverage',
    score_impact: 8,
    extraction_method: 'pdf',
    extraction_confidence: 0.89,
    extracted_text: 'Fast Company\n\nThe Design Genius Behind Figma\'s Revolutionary Interface\n\nAlex Kumar has transformed how millions of designers work...',
    ai_reasoning: 'This is a feature article in Fast Company, a major national publication, specifically about the beneficiary and their work. This clearly meets the published material criterion.',
    created_at: '2024-11-06T10:00:00Z',
    updated_at: '2024-11-12T10:00:00Z',
  },

  // David Okonkwo's Documents (talent-profile-7)
  {
    id: 'doc-6',
    talent_id: 'talent-profile-7',
    title: 'Nature Physics Publication',
    description: 'Published paper on quantum error correction',
    file_url: '/demo/documents/nature-physics-paper.pdf',
    file_name: 'quantum-error-correction.pdf',
    file_type: 'application/pdf',
    file_size: 3400000,
    criterion: O1Criterion.SCHOLARLY_ARTICLES,
    auto_classified_criterion: O1Criterion.SCHOLARLY_ARTICLES,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Peer-reviewed publication in top-tier physics journal.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-20T10:00:00Z',
    review_notes: 'Nature Physics - top-tier publication verified',
    score_impact: 12,
    extraction_method: 'pdf',
    extraction_confidence: 0.96,
    extracted_text: 'Nature Physics\nVolume 20, January 2024\n\nNovel Topological Quantum Error Correction Codes\n\nDavid Okonkwo, et al.\n\nAbstract: We present a new class of topological error correction codes...',
    ai_reasoning: 'Publication in Nature Physics, one of the most prestigious journals in physics, demonstrates scholarly articles of major significance. The paper presents original research on quantum error correction.',
    created_at: '2024-11-18T10:00:00Z',
    updated_at: '2024-11-20T10:00:00Z',
  },
  {
    id: 'doc-7',
    talent_id: 'talent-profile-7',
    title: 'APS Fellowship Certificate',
    description: 'American Physical Society Fellow certificate',
    file_url: '/demo/documents/aps-fellowship.pdf',
    file_name: 'aps-fellow-certificate.pdf',
    file_type: 'application/pdf',
    file_size: 345000,
    criterion: O1Criterion.MEMBERSHIPS,
    auto_classified_criterion: O1Criterion.MEMBERSHIPS,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Elite membership in prestigious scientific society.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-20T10:00:00Z',
    review_notes: 'APS Fellowship verified - elite membership requiring outstanding contributions',
    score_impact: 8,
    extraction_method: 'pdf',
    extraction_confidence: 0.93,
    extracted_text: 'American Physical Society\nCertificate of Fellowship\n\nThis certifies that David Okonkwo has been elected a Fellow of the American Physical Society\nFor outstanding contributions to quantum computing and error correction...',
    ai_reasoning: 'APS Fellowship is an elite distinction granted to less than 0.5% of members. This demonstrates membership in an association requiring outstanding achievements, meeting the memberships criterion.',
    created_at: '2024-11-18T10:00:00Z',
    updated_at: '2024-11-20T10:00:00Z',
  },

  // Yuki Tanaka's Documents (talent-profile-5)
  {
    id: 'doc-8',
    talent_id: 'talent-profile-5',
    title: 'EIP-4844 Authorship Evidence',
    description: 'Ethereum Improvement Proposal documentation showing authorship',
    file_url: '/demo/documents/eip-4844.pdf',
    file_name: 'eip-4844-proto-danksharding.pdf',
    file_type: 'application/pdf',
    file_size: 890000,
    criterion: O1Criterion.ORIGINAL_CONTRIBUTIONS,
    auto_classified_criterion: O1Criterion.ORIGINAL_CONTRIBUTIONS,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Evidence of authoring major protocol improvement adopted by Ethereum network.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-12-01T10:00:00Z',
    review_notes: 'Verified EIP-4844 authorship - major contribution to Ethereum ecosystem',
    score_impact: 15,
    extraction_method: 'pdf',
    extraction_confidence: 0.90,
    extracted_text: 'EIP-4844: Shard Blob Transactions\nStatus: Final\nAuthors: Yuki Tanaka, et al.\n\nAbstract: This EIP introduces a new transaction format for "blob-carrying transactions"...',
    ai_reasoning: 'EIP-4844 (Proto-Danksharding) is one of the most significant Ethereum improvements, enabling scalability advances. Authoring this protocol change demonstrates an original contribution of major significance to the field.',
    created_at: '2024-11-28T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },

  // Elena Popov's Documents (talent-profile-6)
  {
    id: 'doc-9',
    talent_id: 'talent-profile-6',
    title: 'Emmy Award Certificate',
    description: 'Emmy Award for Outstanding Music Composition',
    file_url: '/demo/documents/emmy-award.pdf',
    file_name: 'emmy-certificate-2022.pdf',
    file_type: 'application/pdf',
    file_size: 456000,
    criterion: O1Criterion.AWARDS,
    auto_classified_criterion: O1Criterion.AWARDS,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Major entertainment industry award recognizing excellence.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-25T10:00:00Z',
    review_notes: 'Verified Emmy Award - major national recognition',
    score_impact: 12,
    extraction_method: 'pdf',
    extraction_confidence: 0.95,
    extracted_text: 'Television Academy\nEmmy Award\n\nOutstanding Music Composition for a Limited or Anthology Series, Movie or Special\n\nAwarded to: Elena Popov\nFor: "The Final Season"\nYear: 2022',
    ai_reasoning: 'An Emmy Award is one of the most prestigious awards in television, recognizing the highest achievement. This clearly meets the criterion for nationally recognized prizes or awards for excellence.',
    created_at: '2024-11-22T10:00:00Z',
    updated_at: '2024-11-25T10:00:00Z',
  },
  {
    id: 'doc-10',
    talent_id: 'talent-profile-6',
    title: 'Grammy Nomination Certificate',
    description: 'Official Grammy nomination for Best Score Soundtrack for Visual Media',
    file_url: '/demo/documents/grammy-nomination.pdf',
    file_name: 'grammy-nomination-2023.pdf',
    file_type: 'application/pdf',
    file_size: 234000,
    criterion: O1Criterion.AWARDS,
    auto_classified_criterion: O1Criterion.AWARDS,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Grammy nomination demonstrates national recognition at highest level.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-25T10:00:00Z',
    review_notes: 'Verified Grammy nomination - elite recognition in music',
    score_impact: 10,
    extraction_method: 'pdf',
    extraction_confidence: 0.94,
    extracted_text: 'Recording Academy\n66th Annual Grammy Awards\n\nNomination Certificate\n\nBest Score Soundtrack For Visual Media\nElena Popov - "Echoes of Tomorrow"',
    ai_reasoning: 'A Grammy nomination represents recognition at the highest level of the music industry. While not a win, nomination itself demonstrates extraordinary achievement and places the beneficiary among the elite in their field.',
    created_at: '2024-11-22T10:00:00Z',
    updated_at: '2024-11-25T10:00:00Z',
  },

  // Maria Santos' Documents (talent-profile-3)
  {
    id: 'doc-12',
    talent_id: 'talent-profile-3',
    title: 'NIH Director\'s New Innovator Award',
    description: 'Award letter from NIH for innovative research',
    file_url: '/demo/documents/nih-award.pdf',
    file_name: 'nih-new-innovator-award.pdf',
    file_type: 'application/pdf',
    file_size: 567000,
    criterion: O1Criterion.AWARDS,
    auto_classified_criterion: O1Criterion.AWARDS,
    classification_confidence: ClassificationConfidence.HIGH,
    classification_notes: 'Prestigious NIH award for exceptional early-career scientists.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-28T10:00:00Z',
    review_notes: 'Verified NIH Director\'s Award - highly competitive national recognition',
    score_impact: 12,
    extraction_method: 'pdf',
    extraction_confidence: 0.93,
    extracted_text: 'National Institutes of Health\nOffice of the Director\n\nNIH Director\'s New Innovator Award\n\nDr. Maria Santos\nGeneTech Labs\n\nFor: "Novel CRISPR Delivery Systems for Gene Therapy"',
    ai_reasoning: 'The NIH Director\'s New Innovator Award is one of the most prestigious awards for early-career researchers in biomedical sciences. It is highly competitive and recognizes exceptional creativity and innovation.',
    created_at: '2024-11-26T10:00:00Z',
    updated_at: '2024-11-28T10:00:00Z',
  },
  {
    id: 'doc-13',
    talent_id: 'talent-profile-3',
    title: 'Series B Term Sheet - GeneTech Labs',
    description: 'Evidence of $45M Series B fundraise',
    file_url: '/demo/documents/series-b-termsheet.pdf',
    file_name: 'genetech-series-b.pdf',
    file_type: 'application/pdf',
    file_size: 890000,
    criterion: O1Criterion.CRITICAL_ROLE,
    auto_classified_criterion: O1Criterion.CRITICAL_ROLE,
    classification_confidence: ClassificationConfidence.MEDIUM,
    classification_notes: 'Evidence of leading successful startup to significant funding round.',
    status: DocumentStatus.VERIFIED,
    reviewed_by: 'demo-admin-1',
    reviewed_at: '2024-11-28T10:00:00Z',
    review_notes: 'Verified $45M Series B - demonstrates critical leadership role',
    score_impact: 10,
    extraction_method: 'pdf',
    extraction_confidence: 0.85,
    extracted_text: 'Series B Preferred Stock Purchase Agreement\n\nCompany: GeneTech Labs, Inc.\nInvestment Amount: $45,000,000\nLead Investor: Flagship Pioneering\n\nFounders:\n- Maria Santos, Co-Founder & CSO',
    ai_reasoning: 'Raising a $45M Series B as a co-founder and CSO demonstrates a critical role in a distinguished organization. The beneficiary\'s scientific leadership was essential to securing this substantial investment.',
    created_at: '2024-11-26T10:00:00Z',
    updated_at: '2024-11-28T10:00:00Z',
  },

  // Pending/needs review documents for demo
  {
    id: 'doc-14',
    talent_id: 'talent-profile-4',
    title: 'ESPN Feature Article',
    description: 'Video feature on coaching methods',
    file_url: '/demo/documents/espn-feature.pdf',
    file_name: 'espn-coach-profile.pdf',
    file_type: 'application/pdf',
    file_size: 2300000,
    criterion: O1Criterion.PUBLISHED_MATERIAL,
    auto_classified_criterion: O1Criterion.PUBLISHED_MATERIAL,
    classification_confidence: ClassificationConfidence.MEDIUM,
    classification_notes: 'Media coverage in major sports publication.',
    status: DocumentStatus.NEEDS_REVIEW,
    reviewed_by: null,
    reviewed_at: null,
    review_notes: null,
    score_impact: 7,
    extraction_method: 'pdf+ocr',
    extraction_confidence: 0.72,
    extracted_text: 'ESPN\nThe Science of Winning\nHow James Wilson is revolutionizing Olympic training...',
    ai_reasoning: 'This appears to be published material about the beneficiary from ESPN, a major sports media outlet. Medium confidence as the full article text wasn\'t clearly extractable.',
    created_at: '2024-12-10T10:00:00Z',
    updated_at: '2024-12-10T10:00:00Z',
  },
  {
    id: 'doc-15',
    talent_id: 'talent-profile-8',
    title: 'CFDA Award Photo',
    description: 'Photo of CFDA Award ceremony',
    file_url: '/demo/documents/cfda-award.jpg',
    file_name: 'cfda-fashion-award.jpg',
    file_type: 'image/jpeg',
    file_size: 4500000,
    criterion: O1Criterion.AWARDS,
    auto_classified_criterion: O1Criterion.AWARDS,
    classification_confidence: ClassificationConfidence.LOW,
    classification_notes: 'Image appears to show award ceremony, but text not fully extractable.',
    status: DocumentStatus.PENDING,
    reviewed_by: null,
    reviewed_at: null,
    review_notes: null,
    score_impact: null,
    extraction_method: 'ocr',
    extraction_confidence: 0.45,
    extracted_text: 'CFDA... Fashion... Sophie Laurent... Emerging Designer...',
    ai_reasoning: 'OCR extraction from image has low confidence. The image appears to show a fashion award ceremony, but cannot definitively confirm the award details. Recommend manual review.',
    created_at: '2024-12-15T10:00:00Z',
    updated_at: '2024-12-15T10:00:00Z',
  },
];

// Helper functions
export function getDocumentsByTalent(talentId: string): TalentDocument[] {
  return DEMO_TALENT_DOCUMENTS.filter(doc => doc.talent_id === talentId);
}

export function getDocumentsByCriterion(criterion: O1Criterion): TalentDocument[] {
  return DEMO_TALENT_DOCUMENTS.filter(doc => doc.criterion === criterion);
}

export function getDocumentsByStatus(status: DocumentStatus): TalentDocument[] {
  return DEMO_TALENT_DOCUMENTS.filter(doc => doc.status === status);
}

export function getVerifiedDocuments(): TalentDocument[] {
  return DEMO_TALENT_DOCUMENTS.filter(doc => doc.status === DocumentStatus.VERIFIED);
}

export function getPendingReviewDocuments(): TalentDocument[] {
  return DEMO_TALENT_DOCUMENTS.filter(doc =>
    doc.status === DocumentStatus.PENDING || doc.status === DocumentStatus.NEEDS_REVIEW
  );
}
