/**
 * Mock Data for Demo Mode
 *
 * Comprehensive realistic data for all entities in the O1DMatch platform.
 */

import {
  UserRole,
  VisaStatus,
  DocumentStatus,
  ClassificationConfidence,
  O1Criterion,
  JobStatus,
  ApplicationStatus,
  LetterStatus,
  CommitmentLevel,
  WorkArrangement,
  EngagementType,
  LawyerTier,
  ConnectionStatus,
} from '@/types/enums';

import type {
  Profile,
  TalentProfile,
  MaskedTalentProfile,
  TalentDocument,
  EmployerProfile,
  AgencyProfile,
  AgencyClient,
  JobListing,
  JobApplication,
  InterestLetter,
  LawyerProfile,
  PublicLawyerProfile,
  EvidenceSummary,
} from '@/types/models';

// ============================================================================
// DEMO USERS / PROFILES
// ============================================================================

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'demo-talent-1',
    email: 'sarah.chen@demo.com',
    full_name: 'Sarah Chen',
    role: UserRole.TALENT,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-talent-2',
    email: 'alex.kumar@demo.com',
    full_name: 'Alex Kumar',
    role: UserRole.TALENT,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-talent-3',
    email: 'maria.santos@demo.com',
    full_name: 'Maria Santos',
    role: UserRole.TALENT,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-talent-4',
    email: 'james.wilson@demo.com',
    full_name: 'James Wilson',
    role: UserRole.TALENT,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-04-05T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-talent-5',
    email: 'yuki.tanaka@demo.com',
    full_name: 'Yuki Tanaka',
    role: UserRole.TALENT,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-05-12T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-employer-1',
    email: 'john.martinez@techcorp.demo',
    full_name: 'John Martinez',
    role: UserRole.EMPLOYER,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-employer-2',
    email: 'lisa.johnson@innovate.demo',
    full_name: 'Lisa Johnson',
    role: UserRole.EMPLOYER,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-agency-1',
    email: 'elite@agency.demo',
    full_name: 'Elite Talent Agency',
    role: UserRole.AGENCY,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-lawyer-1',
    email: 'michael.thompson@lawfirm.demo',
    full_name: 'Michael Thompson',
    role: UserRole.LAWYER,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-admin-1',
    email: 'admin@o1dmatch.demo',
    full_name: 'Admin User',
    role: UserRole.ADMIN,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-01-01T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
];

// ============================================================================
// TALENT PROFILES
// ============================================================================

const createEvidenceSummary = (scores: Partial<Record<O1Criterion, { score: number; met: boolean; has: string[]; needs: string[] }>>): EvidenceSummary => {
  const summary: EvidenceSummary = {};
  const criteria: O1Criterion[] = [
    O1Criterion.AWARDS,
    O1Criterion.MEMBERSHIPS,
    O1Criterion.PUBLISHED_MATERIAL,
    O1Criterion.JUDGING,
    O1Criterion.ORIGINAL_CONTRIBUTIONS,
    O1Criterion.SCHOLARLY_ARTICLES,
    O1Criterion.CRITICAL_ROLE,
    O1Criterion.HIGH_SALARY,
  ];

  for (const criterion of criteria) {
    const data = scores[criterion];
    if (data) {
      summary[criterion] = {
        score: data.score,
        max_score: 25,
        met: data.met,
        evidence_count: data.has.length,
        has: data.has,
        needs: data.needs,
      };
    } else {
      summary[criterion] = {
        score: 0,
        max_score: 25,
        met: false,
        evidence_count: 0,
        has: [],
        needs: ['Upload evidence for this criterion'],
      };
    }
  }
  return summary;
};

export const DEMO_TALENT_PROFILES: TalentProfile[] = [
  {
    id: 'talent-profile-1',
    user_id: 'demo-talent-1',
    candidate_id: 'CAND-001234',
    first_name: 'Sarah',
    last_name: 'Chen',
    email: 'sarah.chen@demo.com',
    phone: '+1-555-0101',
    professional_headline: 'AI/ML Research Scientist with 50+ Publications',
    current_job_title: 'Senior Research Scientist',
    current_employer: 'DeepMind',
    industry: 'Artificial Intelligence',
    years_experience: 12,
    seniority: 'Senior',
    skills: ['Machine Learning', 'Deep Learning', 'PyTorch', 'TensorFlow', 'NLP', 'Computer Vision', 'Python', 'Research'],
    education: 'PhD',
    university: 'Stanford University',
    field_of_study: 'Computer Science',
    graduation_year: 2015,
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    willing_to_relocate: true,
    preferred_locations: ['San Francisco', 'New York', 'Seattle', 'Boston'],
    work_arrangement: WorkArrangement.HYBRID,
    engagement_type: EngagementType.FULL_TIME,
    salary_min: 350000,
    salary_preferred: 450000,
    available_start: 'Immediately',
    available_start_date: '2025-01-15',
    linkedin_url: 'https://linkedin.com/in/sarahchen-demo',
    github_url: 'https://github.com/sarahchen-demo',
    google_scholar_url: 'https://scholar.google.com/citations?user=demo',
    personal_website: 'https://sarahchen.ai',
    resume_url: '/demo/resumes/sarah-chen.pdf',
    resume_filename: 'sarah-chen-resume.pdf',
    o1_score: 92,
    visa_status: VisaStatus.READY_TO_FILE,
    criteria_met: [O1Criterion.AWARDS, O1Criterion.SCHOLARLY_ARTICLES, O1Criterion.ORIGINAL_CONTRIBUTIONS, O1Criterion.JUDGING, O1Criterion.CRITICAL_ROLE],
    evidence_summary: createEvidenceSummary({
      [O1Criterion.AWARDS]: { score: 22, met: true, has: ['ACM Best Paper Award 2023', 'NeurIPS Outstanding Paper 2022', 'Google Research Award'], needs: [] },
      [O1Criterion.SCHOLARLY_ARTICLES]: { score: 25, met: true, has: ['52 peer-reviewed publications', 'H-index: 34', '8,500+ citations'], needs: [] },
      [O1Criterion.ORIGINAL_CONTRIBUTIONS]: { score: 20, met: true, has: ['Invented novel attention mechanism', '3 patents granted', 'Open source framework with 10k+ stars'], needs: [] },
      [O1Criterion.JUDGING]: { score: 15, met: true, has: ['NeurIPS Program Committee', 'ICML Reviewer', 'NSF Grant Reviewer'], needs: [] },
      [O1Criterion.CRITICAL_ROLE]: { score: 10, met: true, has: ['Led 15-person research team', 'Principal Investigator on $2M project'], needs: [] },
    }),
    score_updated_at: '2024-12-01T10:00:00Z',
    publications_count: 52,
    h_index: 34,
    citations_count: 8500,
    patents_count: 3,
    profile_photo_url: null,
    is_public: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'talent-profile-2',
    user_id: 'demo-talent-2',
    candidate_id: 'CAND-002345',
    first_name: 'Alex',
    last_name: 'Kumar',
    email: 'alex.kumar@demo.com',
    phone: '+1-555-0102',
    professional_headline: 'Award-Winning Product Designer & UX Leader',
    current_job_title: 'Head of Design',
    current_employer: 'Figma',
    industry: 'Design & Technology',
    years_experience: 10,
    seniority: 'Director',
    skills: ['Product Design', 'UX Research', 'Design Systems', 'Figma', 'Prototyping', 'User Testing', 'Leadership'],
    education: 'Masters',
    university: 'Rhode Island School of Design',
    field_of_study: 'Industrial Design',
    graduation_year: 2014,
    city: 'New York',
    state: 'NY',
    country: 'USA',
    willing_to_relocate: true,
    preferred_locations: ['New York', 'San Francisco', 'Los Angeles'],
    work_arrangement: WorkArrangement.REMOTE,
    engagement_type: EngagementType.FULL_TIME,
    salary_min: 280000,
    salary_preferred: 350000,
    available_start: '2 weeks notice',
    available_start_date: '2025-02-01',
    linkedin_url: 'https://linkedin.com/in/alexkumar-demo',
    github_url: null,
    google_scholar_url: null,
    personal_website: 'https://alexkumar.design',
    resume_url: '/demo/resumes/alex-kumar.pdf',
    resume_filename: 'alex-kumar-resume.pdf',
    o1_score: 78,
    visa_status: VisaStatus.STRONG_CANDIDATE,
    criteria_met: [O1Criterion.AWARDS, O1Criterion.PUBLISHED_MATERIAL, O1Criterion.JUDGING, O1Criterion.CRITICAL_ROLE],
    evidence_summary: createEvidenceSummary({
      [O1Criterion.AWARDS]: { score: 20, met: true, has: ['Red Dot Design Award 2023', 'Apple Design Award 2022', 'Webby Award Winner'], needs: [] },
      [O1Criterion.PUBLISHED_MATERIAL]: { score: 18, met: true, has: ['Featured in Fast Company', 'Wired Magazine Interview', 'Design Week Profile'], needs: [] },
      [O1Criterion.JUDGING]: { score: 15, met: true, has: ['Adobe Design Achievement Awards Judge', 'Awwwards Jury Member'], needs: [] },
      [O1Criterion.CRITICAL_ROLE]: { score: 25, met: true, has: ['Built design team from 3 to 25', 'Led redesign generating $50M revenue'], needs: [] },
    }),
    score_updated_at: '2024-12-01T10:00:00Z',
    publications_count: 0,
    h_index: 0,
    citations_count: 0,
    patents_count: 2,
    profile_photo_url: null,
    is_public: true,
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'talent-profile-3',
    user_id: 'demo-talent-3',
    candidate_id: 'CAND-003456',
    first_name: 'Maria',
    last_name: 'Santos',
    email: 'maria.santos@demo.com',
    phone: '+1-555-0103',
    professional_headline: 'Biotech Entrepreneur & Molecular Biologist',
    current_job_title: 'Co-Founder & CSO',
    current_employer: 'GeneTech Labs',
    industry: 'Biotechnology',
    years_experience: 15,
    seniority: 'Executive',
    skills: ['Molecular Biology', 'CRISPR', 'Gene Therapy', 'Drug Discovery', 'Startup Leadership', 'FDA Regulations', 'Fundraising'],
    education: 'PhD',
    university: 'MIT',
    field_of_study: 'Molecular Biology',
    graduation_year: 2012,
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    willing_to_relocate: false,
    preferred_locations: ['Boston', 'Cambridge'],
    work_arrangement: WorkArrangement.ON_SITE,
    engagement_type: EngagementType.FULL_TIME,
    salary_min: 400000,
    salary_preferred: 500000,
    available_start: '3 months notice',
    available_start_date: '2025-04-01',
    linkedin_url: 'https://linkedin.com/in/mariasantos-demo',
    github_url: null,
    google_scholar_url: 'https://scholar.google.com/citations?user=maria-demo',
    personal_website: null,
    resume_url: '/demo/resumes/maria-santos.pdf',
    resume_filename: 'maria-santos-resume.pdf',
    o1_score: 88,
    visa_status: VisaStatus.READY_TO_FILE,
    criteria_met: [O1Criterion.AWARDS, O1Criterion.SCHOLARLY_ARTICLES, O1Criterion.ORIGINAL_CONTRIBUTIONS, O1Criterion.HIGH_SALARY, O1Criterion.CRITICAL_ROLE],
    evidence_summary: createEvidenceSummary({
      [O1Criterion.AWARDS]: { score: 18, met: true, has: ['NIH Director\'s New Innovator Award', 'Forbes 30 Under 30'], needs: [] },
      [O1Criterion.SCHOLARLY_ARTICLES]: { score: 22, met: true, has: ['38 publications in Nature, Science, Cell', 'H-index: 28'], needs: [] },
      [O1Criterion.ORIGINAL_CONTRIBUTIONS]: { score: 23, met: true, has: ['5 patents in gene therapy', 'Novel CRISPR delivery method'], needs: [] },
      [O1Criterion.HIGH_SALARY]: { score: 15, met: true, has: ['Top 1% compensation in biotech', 'Equity worth $5M+'], needs: [] },
      [O1Criterion.CRITICAL_ROLE]: { score: 10, met: true, has: ['Raised $45M Series B', 'Built team of 60 scientists'], needs: [] },
    }),
    score_updated_at: '2024-12-01T10:00:00Z',
    publications_count: 38,
    h_index: 28,
    citations_count: 4200,
    patents_count: 5,
    profile_photo_url: null,
    is_public: true,
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'talent-profile-4',
    user_id: 'demo-talent-4',
    candidate_id: 'CAND-004567',
    first_name: 'James',
    last_name: 'Wilson',
    email: 'james.wilson@demo.com',
    phone: '+1-555-0104',
    professional_headline: 'Olympic Coach & Sports Performance Expert',
    current_job_title: 'Head Performance Coach',
    current_employer: 'US Olympic Committee',
    industry: 'Sports & Athletics',
    years_experience: 18,
    seniority: 'Senior',
    skills: ['Athletic Performance', 'Sports Psychology', 'Team Leadership', 'Data Analytics', 'Injury Prevention', 'Olympic Preparation'],
    education: 'Masters',
    university: 'University of Oregon',
    field_of_study: 'Sports Science',
    graduation_year: 2008,
    city: 'Colorado Springs',
    state: 'CO',
    country: 'USA',
    willing_to_relocate: true,
    preferred_locations: ['Los Angeles', 'Denver', 'Phoenix'],
    work_arrangement: WorkArrangement.ON_SITE,
    engagement_type: EngagementType.FULL_TIME,
    salary_min: 200000,
    salary_preferred: 280000,
    available_start: '1 month notice',
    available_start_date: '2025-02-15',
    linkedin_url: 'https://linkedin.com/in/jameswilson-demo',
    github_url: null,
    google_scholar_url: null,
    personal_website: 'https://jameswilsoncoaching.com',
    resume_url: '/demo/resumes/james-wilson.pdf',
    resume_filename: 'james-wilson-resume.pdf',
    o1_score: 72,
    visa_status: VisaStatus.STRONG_CANDIDATE,
    criteria_met: [O1Criterion.AWARDS, O1Criterion.PUBLISHED_MATERIAL, O1Criterion.JUDGING, O1Criterion.CRITICAL_ROLE],
    evidence_summary: createEvidenceSummary({
      [O1Criterion.AWARDS]: { score: 20, met: true, has: ['NSCA Coach of the Year 2022', 'Olympic Medal-Winning Coach (3 athletes)'], needs: [] },
      [O1Criterion.PUBLISHED_MATERIAL]: { score: 15, met: true, has: ['ESPN Feature', 'Sports Illustrated Profile', 'Olympic Channel Documentary'], needs: [] },
      [O1Criterion.JUDGING]: { score: 12, met: true, has: ['USA Track & Field Selection Committee', 'NCAA Coaching Awards Committee'], needs: [] },
      [O1Criterion.CRITICAL_ROLE]: { score: 25, met: true, has: ['Head Coach for 2024 Olympic Team', 'Led program to 15 medals'], needs: [] },
    }),
    score_updated_at: '2024-12-01T10:00:00Z',
    publications_count: 5,
    h_index: 0,
    citations_count: 0,
    patents_count: 0,
    profile_photo_url: null,
    is_public: true,
    created_at: '2024-04-05T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'talent-profile-5',
    user_id: 'demo-talent-5',
    candidate_id: 'CAND-005678',
    first_name: 'Yuki',
    last_name: 'Tanaka',
    email: 'yuki.tanaka@demo.com',
    phone: '+1-555-0105',
    professional_headline: 'Blockchain Architect & Web3 Pioneer',
    current_job_title: 'Principal Engineer',
    current_employer: 'Ethereum Foundation',
    industry: 'Blockchain & Cryptocurrency',
    years_experience: 8,
    seniority: 'Principal',
    skills: ['Solidity', 'Smart Contracts', 'Ethereum', 'DeFi', 'Cryptography', 'Rust', 'Go', 'Protocol Design'],
    education: 'Masters',
    university: 'University of Tokyo',
    field_of_study: 'Cryptography',
    graduation_year: 2016,
    city: 'Remote',
    state: null,
    country: 'Japan',
    willing_to_relocate: true,
    preferred_locations: ['San Francisco', 'Miami', 'Singapore'],
    work_arrangement: WorkArrangement.REMOTE,
    engagement_type: EngagementType.FULL_TIME,
    salary_min: 320000,
    salary_preferred: 400000,
    available_start: 'Immediately',
    available_start_date: '2025-01-01',
    linkedin_url: 'https://linkedin.com/in/yukitanaka-demo',
    github_url: 'https://github.com/yukitanaka-demo',
    google_scholar_url: null,
    personal_website: 'https://yuki.eth',
    resume_url: '/demo/resumes/yuki-tanaka.pdf',
    resume_filename: 'yuki-tanaka-resume.pdf',
    o1_score: 68,
    visa_status: VisaStatus.PROFILE_BUILDING,
    criteria_met: [O1Criterion.ORIGINAL_CONTRIBUTIONS, O1Criterion.SCHOLARLY_ARTICLES, O1Criterion.HIGH_SALARY],
    evidence_summary: createEvidenceSummary({
      [O1Criterion.ORIGINAL_CONTRIBUTIONS]: { score: 25, met: true, has: ['Authored EIP-4844 (Proto-Danksharding)', 'Created widely-used DeFi protocol', 'Open source with 25k+ GitHub stars'], needs: [] },
      [O1Criterion.SCHOLARLY_ARTICLES]: { score: 18, met: true, has: ['12 peer-reviewed papers on cryptography', 'Speaker at Devcon 5 times'], needs: [] },
      [O1Criterion.HIGH_SALARY]: { score: 25, met: true, has: ['Top 0.1% in blockchain compensation', 'Token grants worth $2M+'], needs: [] },
    }),
    score_updated_at: '2024-12-01T10:00:00Z',
    publications_count: 12,
    h_index: 8,
    citations_count: 450,
    patents_count: 0,
    profile_photo_url: null,
    is_public: true,
    created_at: '2024-05-12T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'talent-profile-6',
    user_id: 'demo-talent-6',
    candidate_id: 'CAND-006789',
    first_name: 'Elena',
    last_name: 'Popov',
    email: 'elena.popov@demo.com',
    phone: '+1-555-0106',
    professional_headline: 'Grammy-Nominated Composer & Music Producer',
    current_job_title: 'Composer',
    current_employer: 'Self-Employed',
    industry: 'Music & Entertainment',
    years_experience: 14,
    seniority: 'Senior',
    skills: ['Film Scoring', 'Music Production', 'Orchestration', 'Ableton Live', 'Logic Pro', 'Classical Composition'],
    education: 'Masters',
    university: 'Juilliard School',
    field_of_study: 'Music Composition',
    graduation_year: 2011,
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    willing_to_relocate: false,
    preferred_locations: ['Los Angeles'],
    work_arrangement: WorkArrangement.FLEXIBLE,
    engagement_type: EngagementType.PROJECT_BASED,
    salary_min: 250000,
    salary_preferred: 400000,
    available_start: 'Project dependent',
    available_start_date: null,
    linkedin_url: 'https://linkedin.com/in/elenapopov-demo',
    github_url: null,
    google_scholar_url: null,
    personal_website: 'https://elenapopovmusic.com',
    resume_url: '/demo/resumes/elena-popov.pdf',
    resume_filename: 'elena-popov-resume.pdf',
    o1_score: 85,
    visa_status: VisaStatus.READY_TO_FILE,
    criteria_met: [O1Criterion.AWARDS, O1Criterion.PUBLISHED_MATERIAL, O1Criterion.CRITICAL_ROLE, O1Criterion.HIGH_SALARY],
    evidence_summary: createEvidenceSummary({
      [O1Criterion.AWARDS]: { score: 25, met: true, has: ['Grammy Nomination 2023', 'Emmy Award Winner', 'BMI Film Music Award'], needs: [] },
      [O1Criterion.PUBLISHED_MATERIAL]: { score: 20, met: true, has: ['Rolling Stone Feature', 'Variety Interview', 'Billboard Profile'], needs: [] },
      [O1Criterion.CRITICAL_ROLE]: { score: 22, met: true, has: ['Composed scores for 5 major films', 'Music director for Netflix series'], needs: [] },
      [O1Criterion.HIGH_SALARY]: { score: 18, met: true, has: ['$500k+ annual from film scores', 'Streaming royalties in top 1%'], needs: [] },
    }),
    score_updated_at: '2024-12-01T10:00:00Z',
    publications_count: 0,
    h_index: 0,
    citations_count: 0,
    patents_count: 0,
    profile_photo_url: null,
    is_public: true,
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'talent-profile-7',
    user_id: 'demo-talent-7',
    candidate_id: 'CAND-007890',
    first_name: 'David',
    last_name: 'Okonkwo',
    email: 'david.okonkwo@demo.com',
    phone: '+1-555-0107',
    professional_headline: 'Quantum Computing Researcher & Physicist',
    current_job_title: 'Research Scientist',
    current_employer: 'IBM Quantum',
    industry: 'Quantum Computing',
    years_experience: 9,
    seniority: 'Senior',
    skills: ['Quantum Algorithms', 'Qiskit', 'Python', 'Physics', 'Error Correction', 'Superconducting Qubits'],
    education: 'PhD',
    university: 'Caltech',
    field_of_study: 'Quantum Physics',
    graduation_year: 2018,
    city: 'Yorktown Heights',
    state: 'NY',
    country: 'USA',
    willing_to_relocate: true,
    preferred_locations: ['San Francisco', 'Boston', 'Seattle'],
    work_arrangement: WorkArrangement.HYBRID,
    engagement_type: EngagementType.FULL_TIME,
    salary_min: 280000,
    salary_preferred: 350000,
    available_start: '2 months notice',
    available_start_date: '2025-03-01',
    linkedin_url: 'https://linkedin.com/in/davidokonkwo-demo',
    github_url: 'https://github.com/davidokonkwo-demo',
    google_scholar_url: 'https://scholar.google.com/citations?user=david-demo',
    personal_website: null,
    resume_url: '/demo/resumes/david-okonkwo.pdf',
    resume_filename: 'david-okonkwo-resume.pdf',
    o1_score: 75,
    visa_status: VisaStatus.STRONG_CANDIDATE,
    criteria_met: [O1Criterion.SCHOLARLY_ARTICLES, O1Criterion.ORIGINAL_CONTRIBUTIONS, O1Criterion.MEMBERSHIPS],
    evidence_summary: createEvidenceSummary({
      [O1Criterion.SCHOLARLY_ARTICLES]: { score: 23, met: true, has: ['25 publications', 'Nature Physics paper', 'H-index: 18'], needs: [] },
      [O1Criterion.ORIGINAL_CONTRIBUTIONS]: { score: 20, met: true, has: ['Novel error correction code', '2 patents pending', 'Qiskit core contributor'], needs: [] },
      [O1Criterion.MEMBERSHIPS]: { score: 15, met: true, has: ['APS Fellow', 'IEEE Senior Member'], needs: [] },
      [O1Criterion.AWARDS]: { score: 17, met: false, has: ['IBM Research Division Award'], needs: ['Need national/international recognition'] },
    }),
    score_updated_at: '2024-12-01T10:00:00Z',
    publications_count: 25,
    h_index: 18,
    citations_count: 1800,
    patents_count: 2,
    profile_photo_url: null,
    is_public: true,
    created_at: '2024-07-15T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'talent-profile-8',
    user_id: 'demo-talent-8',
    candidate_id: 'CAND-008901',
    first_name: 'Sophie',
    last_name: 'Laurent',
    email: 'sophie.laurent@demo.com',
    phone: '+1-555-0108',
    professional_headline: 'Fashion Designer & Creative Director',
    current_job_title: 'Creative Director',
    current_employer: 'Maison Laurent',
    industry: 'Fashion & Luxury',
    years_experience: 16,
    seniority: 'Executive',
    skills: ['Fashion Design', 'Brand Strategy', 'Luxury Marketing', 'Trend Forecasting', 'Sustainability', 'Team Leadership'],
    education: 'Bachelors',
    university: 'Central Saint Martins',
    field_of_study: 'Fashion Design',
    graduation_year: 2009,
    city: 'New York',
    state: 'NY',
    country: 'USA',
    willing_to_relocate: true,
    preferred_locations: ['New York', 'Los Angeles', 'Paris'],
    work_arrangement: WorkArrangement.HYBRID,
    engagement_type: EngagementType.FULL_TIME,
    salary_min: 350000,
    salary_preferred: 500000,
    available_start: '3 months notice',
    available_start_date: '2025-04-15',
    linkedin_url: 'https://linkedin.com/in/sophielaurent-demo',
    github_url: null,
    google_scholar_url: null,
    personal_website: 'https://maisonlaurent.com',
    resume_url: '/demo/resumes/sophie-laurent.pdf',
    resume_filename: 'sophie-laurent-resume.pdf',
    o1_score: 82,
    visa_status: VisaStatus.READY_TO_FILE,
    criteria_met: [O1Criterion.AWARDS, O1Criterion.PUBLISHED_MATERIAL, O1Criterion.CRITICAL_ROLE, O1Criterion.HIGH_SALARY],
    evidence_summary: createEvidenceSummary({
      [O1Criterion.AWARDS]: { score: 22, met: true, has: ['CFDA Award Winner', 'British Fashion Award', 'Woolmark Prize Finalist'], needs: [] },
      [O1Criterion.PUBLISHED_MATERIAL]: { score: 20, met: true, has: ['Vogue Cover Story', 'Elle Interview', 'WWD Feature'], needs: [] },
      [O1Criterion.CRITICAL_ROLE]: { score: 22, met: true, has: ['Built brand to $100M valuation', 'Dressed A-list celebrities', 'Met Gala designs'], needs: [] },
      [O1Criterion.HIGH_SALARY]: { score: 18, met: true, has: ['Top 1% in fashion industry', '$50M+ brand equity'], needs: [] },
    }),
    score_updated_at: '2024-12-01T10:00:00Z',
    publications_count: 0,
    h_index: 0,
    citations_count: 0,
    patents_count: 4,
    profile_photo_url: null,
    is_public: true,
    created_at: '2024-08-20T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
];

// Add more talent profiles to DEMO_PROFILES
DEMO_PROFILES.push(
  {
    id: 'demo-talent-6',
    email: 'elena.popov@demo.com',
    full_name: 'Elena Popov',
    role: UserRole.TALENT,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-talent-7',
    email: 'david.okonkwo@demo.com',
    full_name: 'David Okonkwo',
    role: UserRole.TALENT,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-07-15T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'demo-talent-8',
    email: 'sophie.laurent@demo.com',
    full_name: 'Sophie Laurent',
    role: UserRole.TALENT,
    avatar_url: null,
    is_verified: true,
    created_at: '2024-08-20T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  }
);

// Helper to create masked talent profile
export function maskTalentProfile(talent: TalentProfile): MaskedTalentProfile {
  return {
    candidate_id: talent.candidate_id,
    o1_score: talent.o1_score,
    visa_status: talent.visa_status,
    current_job_title: talent.current_job_title,
    industry: talent.industry,
    years_experience: talent.years_experience,
    seniority: talent.seniority,
    skills: talent.skills,
    education: talent.education,
    city: talent.city,
    state: talent.state,
    willing_to_relocate: talent.willing_to_relocate,
    preferred_locations: talent.preferred_locations,
    work_arrangement: talent.work_arrangement,
    engagement_type: talent.engagement_type,
    salary_min: talent.salary_min,
    criteria_met: talent.criteria_met,
    evidence_summary: talent.evidence_summary,
  };
}

export const DEMO_MASKED_TALENTS: MaskedTalentProfile[] = DEMO_TALENT_PROFILES.map(maskTalentProfile);
